### ISSUE TITLE
Investigate rust's handling of other arithmetic operations and bit widths

### ISSUE THREAD

**Issue by keram88** [keram88/smack#2]
Test behavior for data types: (u|s)8, (u|s)16
Test behaviors for arithmetic/logical operators: ~, &, ^, *, +, %, >>, <<, -, |, /

**Comment by keram88** [comment]
We should check what shifting left by an amount bigger than the bit width does.

**Comment by MichaelFQuigley** [comment]
I tried some of the logical ops earlier (|^&), and they don't verify in either C or Rust, so I'm not sure if we would want to worry about this too much right now.

**Comment by keram88** [comment]
You need --bitprecise

**Comment by MichaelFQuigley** [comment]
Ah. Thanks.

**Comment by keram88** [comment]
These seem to be working.
